version: '3.1'
services:
  postgress:
    image: postgres:16
    restart: always
    container_name: postgrescqrs
    environment:
      POSTGRES_DB: accountsquery
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: sa
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:8.5
    restart: always
    container_name: pgadmin
    depends_on:
      - postgress
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sa@me.com
      PGADMIN_DEFAULT_PASSWORD: sa
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  mongo:
    image: mongo
    restart: always
    container_name: mongocqrs
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoui
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sa
      ME_CONFIG_MONGODB_ADMINPASSWORD: sa
      ME_CONFIG_MONGODB_URL: mongodb://sa:sa@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafkaui
    depends_on:
      - kafka
    ports:
      - 8083:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
