server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: sa
      password: sa
      database: admin
    kafka:
      producer:
        bootstrap-servers: localhost:9092
